version: '3'

services:
  node:
    build: docker/node
    user: 1000:1000
    volumes:
      - ./:/app
      - $HOME/.Xauthority:/home/node/.Xauthority
      - ./docker/config:/home/node/.config/.launcher
    working_dir: /app
    environment:
      DISPLAY: $DISPLAY
      NODE_ENV: development
    network_mode: host