FROM node:10-slim

RUN apt-get update
RUN apt-get install -y \
    xvfb \
    xauth \
    libgtk-3-dev \
    libnss3 \
    libxss1 \
    libasound2-dev \
    libdbus-1-dev \
    build-essential \
    clang \
    libnotify-dev \
    libgnome-keyring-dev \
    libgconf2-dev \
    libcap-dev \
    libgtk2.0-dev \
    libgconf-2-4 \
    libasound2 \
    libxtst6 \
    libgtkextra-dev